### ISSUE TITLE
R15 [OceanDAO Eng WG] Prepare Round - Review Schedule & Roadmap - Team sync

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/oceandao#148]
- [x] Review schedule for R15
- [x] Review and determine what new initiatives we are implementing for Round 15
 - [x] Update internal roadmap
