### ISSUE TITLE
[Voting][Sybil][BrightID][Snapshot] Implement BrightID for Sybil-tolerance support & integrate into Snapshot.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#15]
As defined inside epic:
Quadratic Voting. Vote = sqrt(OCEAN held). Theory: Glen Weyl "Radical Markets" book. Popularized by Radical Exchange community, and Gitcoin quadratic funding.

QV is susceptible to Sybil attacks aka "attack of the clones": ie one person creates many wallets in order to get much more influence. To address, we'd need a mechanism for Sybil Tolerance. Eg some identity system, or (even more lightweight) some "proof of unique human"

Snapshot has an example voting that uses BrightID, here: https://snapshot.org/#/strategy/brightid. This may be enough for Sybil tolerance

### [Deliverable 1 - User Registry]
- [x] Deploy BrightID User registry: https://github.com/clrfund/monorepo/blob/develop/contracts/contracts/userRegistry/BrightIdUserRegistry.sol
- [x] Deploy BrightID registry contract in mainnet (perhaps we could leverage the marketplace, so they are together and have no distinction)
- [ ] Update documentation so people can interact w/ mainnet contract

### [Deliverable 2 - Snapshot Strategy]
This is an example strategy that is verified by brightID registry: https://snapshot.org/#/strategy/brightid

 A) Create 1 master strategy that encompasses every source we implement (uni2, bancor, etc..) => ocean_master_brightid
 B) Create N BrightId strategies for each source we implement (uni2_brightId, bancor_brightid, ocean_market_brightid)
DOD - Strategy Requirements - Bonus:

 Implement strategy parameter so a multiplier can be passed in, to return a final score.
I.E. Extra 50% votes if registered via BrightID.

### [Deliverable 3- Registry Frontend]
- [ ] Deploy registry frontend to facilitate onboarding. Make it easy to register (Anyone can register into brightID to receive bonus votes)

DoD:
- [x] Setup a BrightID registry
- [x] Configure Snapshot + BrightID strategy
- [x] Deploy & validate test w/ BrightID support
- [x] Configure DAOBot to deploy proposals w/ BrightID Strategy
- [x] Deploy Frontend to make it accessible

**Comment by idiom-bytes** [comment]
@AnaLoznianu I updated task to outline **deliverables (1)(2)(3)**.
Can you help me turn this into an epic w/ 3 smaller tasks.
