### ISSUE TITLE
R16 [OceanDAO Eng WG] Prepare Round - Review Schedule & Roadmap - Team sync

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/oceandao#175]
- [x] Review schedule for R16
- [x] Review and determine what new initiatives we are implementing for Round 16
 - [x] Update internal roadmap
