### ISSUE TITLE
PGWG: Update Tracker to track and help with "Onboarding New Projects"

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#245]
### Problem:
Right now the guidance tracker is good for us reviewing proposals, but doesn't tell us much about the project and whether we were able to onboard them.

There are other details inside that spreadsheet that could also be removed from there.

## DoD:
- [ ] PGWG Backend Tools have been spting into 2 docs + updated everywhere in documentation: Intake Forms & Guide Tracker
- [ ] Guide Tracker has been updated to only have 2 sheets.
- [ ] Guide Tracker Sheet #1 - Proposal Reviews - Has all the information needed so we can complete our Proposal Review Journey.
- [ ] Guide Tracker Sheet #2 - Project Onboarding - Has all the information needed so we can effectively onboard projects and track which projects we may have failed to contact/onboard.
