### ISSUE TITLE
[Epic] Retroactive funding + R21 and beyond

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#584]
This is a macro ticket to track the work that needs to be delivered for R21 and beyond.

# DoD:
- [ ] Retroactive Grants - Admin Portal [oceandao-617](https://github.com/oceanprotocol/oceandao/issues/617)
- [ ] Retroactive grants proposal ux workflow [proposal-portal-200](https://github.com/oceanprotocol/oceandao-proposal-portal/issues/200)

# DoD Ops:
- [ ] Retroactive grants workflow is communicated and operated manually via Airtable (https://github.com/oceanprotocol/oceandao/issues/616)
- [ ] Retroactive grants workflow is handled manually in the backend via mongo (TBD)
- [ ] Update proposals to adjust existing proposals & discretionary grants (https://github.com/oceanprotocol/oceandao/issues/526)
