### ISSUE TITLE
R13 [OceanDAO Eng WG] Prepare Round - Review Schedule & Roadmap - Team sync

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#70]
- [x] Review schedule for R13
- [x] Review and determine what new initiatives we are implementing for Round 13
 - [x] Update internal roadmap
