### ISSUE TITLE
Formalize + Implement the "Onboard New Members" Process

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#85]
#### Problem
The Project-Guiding Working Group (PGWG) needs to have established members that can help execute the processes & workflows inside this WG. 

In order to do this, we have to have a process & actively onboard new members into the WG that can help execute the mission of this WG.

#### Concepts
- Define parameters that are required for new members to join the WG. Example #1: You need the support from 3 existing members to join. Example #2: You need an Ambassador NFT.
- Create a form that enables new members to register themselves. Example: [Near Protocol - Community Managers](https://nearverse.typeform.com/CommunityMods)
- Make sure that part of their application & welcoming process includes onboarding, explaining other processes, tooling, and other requirements such as a wallet to register into the Coordinape circle.
- Create a process to celebrate/welcome new members into the WG.

#### Towards Solutions
- Identify what needs to take place to provide a V0.1 for the "Onboard New Members" process
**Key Takeaway** - _V0.1 should be extremely simple at first so we can try to launchpad support for R13 right away._

#### V0.1 Membership Process
- ETA: Dec 21st, 2021
- Goal for DOD => Onboard & activate 5 members by next Submission Deadline

#### DOD:
- [x] V0.1 for this process has been fleshed out
- [x] Process has been discussed, formalized, and deployed into the WG
- [x] WG has executed this process a few times and onboarded new members that were not part of the core team that established the WG
- [x] WG has gathered feedback from participants and improved on this process

**Comment by drprk** [comment]
Although I had outlined various other possibilities here 

https://github.com/oceanprotocol/oceandao/issues/83#issuecomment-996511527

I believe the best option that we can have is a separate Discourse with admin features that are suited to the desirable conceps that we require.

**Concepts:**

- Existing parameters are good, we can outline them as follows, with a few suggestions.

1. Assign PG-leaders as a new role on Discord, and allow new members to ping 'PG-Leaders' anytime so that the approval can be done for Members-onboarding.
2. We ensure that the members on-boarding process on discourse has a form-enabled process (Assuming that is likely). In either case its better to avoid having the users sign *yet another form* with additional logins
3. Onboarding Process to have: 'onboarding, explaining other processes, tooling, and other requirements such as a wallet to register into the Coordinape circle'
4. PG-leaders to be briefed on a friendly welcoming process

**Key Insight:** Ocean Ambassadors group is going to have similar on-boarding process with a relatively easier way of onboarding. I'm helping the process happen with OceanAmbassadors group.

**Summary insight:**

Given that users are already familiar to the Port site, it makes sense to have a frictionless onboarding process they are familiar with. Even though it might come with a cumbersome process of creating a newer discourse site, we will begin to have a completely efficient process with customized admin options that is tailor-made to our needs.

![image](https://user-images.githubusercontent.com/88657058/146521573-8ea834c1-595a-41c5-8b53-b02b348b836e.png)

Lot of tools such as https://sourcecred.io/ can also be utilized to have incentivizing PG-WG users as they level up in guiding lot of projects that are in-bound.

All of these of course, can be shipped for later versions, while experimenting a very friction-less way for V0.1

**Comment by drprk** [comment]
Also would invite the following group to work with us, as part of their deliverables. Since they are relatively a newer group, we can see if they could add value to us directly by helping us on-board newer members with their micro-site features. It can be an attractive non-commercial NFT to start with and we can probably add good incentives along our roadmap.

https://port.oceanprotocol.com/t/visualization-of-data-nfts/1152

One of their member, is on our discord channel (  ramz#4530 ), he had attended the recent Core-tech audio chat recently.

**Comment by idiom-bytes** [comment]
> I believe the best option that we can have is a separate Discourse with admin features that are suited to the desirable conceps that we require.

I'm wondering what these requirements may be?

I believe communities like Ambassadors, Outreach Ship, Tech Ship are doing their thing, but there is very little visibility into them, and their current channels in OceanDAO sit empty.

My personal recommendation is to increase engagement & activity inside of WG channels within OceanDAO.

https://github.com/oceanprotocol/oceandao/issues/39

> 1. Assign PG-leaders/PG-Evaluators as a new role on Discord, and allow new members to ping 'PG-Leaders' anytime so that the approval can be done for Members-onboarding.
> 2. We ensure that the members on-boarding process on discourse has a form-enabled process (Assuming that is likely). In either case its better to avoid having the users sign yet another form with additional logins
> 3. Onboarding Process to have: 'onboarding, explaining other processes, tooling, and other requirements such as a wallet to register into the Coordinape circle'
> 4. PG-leaders to be briefed on a friendly welcoming process

I agree with most of this (please see my first response inside this comment).
1. We can create new roles inside of OceanDAO Discord so anyone can find members inside of the PGWG.
2. The [PGWG Outline](https://docs.google.com/document/d/1kw4UwJHZaCf5PKvU3ONoN5nSj-r5zZAX2KJCqzJFT7M/edit) should explain the onboarding process, link to forms, etc.. This could be summarized & pinned to the #PGWG channel, and constantly referred to so anyone can join. I propose we simply use Google Forms & Spreadsheets for now to avoid people from having to create more accounts, or familiarizing themselves with new tooling (everyone knows Docs & Excel)
3. See #2 above.
4. I agree.

**Comment by drprk** [comment]
> Current Ocean Ambassadors Activity

I agree with what you have pointed out. I believe the processes of onboarding members are yet to take effect, with plans to execute this from January. 

https://docs.google.com/presentation/d/1JBrm0oEJHdqHAs8Llyx6tA9DR6R6VQ0EYiILn8aUSLg/edit#slide=id.p1

The current channels of communication have been mostly on Telegram and Weekly/biweekly zoom calls, but that has been mostly in terms of defining the roadmap for Early 2022. We should have a process in place along with the Website that is due to come. More on that to be expressed later.

In the meantime, it is completely agreeable to have WG-Channel activities until then for v0.1 using existing Port | Discord pairs. The only concern would be keeping track of activities during each PG-WG calls, which I believe should be a coordinape responsibility to ensure that there is an executable summary of each calls & henceforth we avoid the problem of having users scroll through 20+ messages.

#39 is very relevant, we should have a call with Laurent as to how we intend to merge redundancies. There needs to be a clarity if we need to proceed with a Telegram community for Ambassadors aka, easier onboarding of individuals rather than having Silos with Inns and Ships, which could use some improvements.

-----------

> Creating new roles

Agreed.

> PG-WG Outline

Agreed. It's good to see that we have evolved from initial Stewardship where it was not necessarily clear in terms of how it was going to work. The Working groups make more sense now.

> Relax "500 Ocean for existing receivers" #2 

So do we propose this format for returning grantees? 
However my original point of was more in line with the PG-WG outline which seems in-line with the Outline document you had posted

**Comment by MeMent0L** [comment]
> I believe communities like Ambassadors, Outreach Ship, Tech Ship are doing their thing, but there is very little visibility into them, and their current channels in OceanDAO sit empty.
> 
> My personal recommendation is to increase engagement & activity inside of WG channels within OceanDAO.
> 
> #39

@idiom-bytes you are part of the Ambassador Trello and Telegram and monthly Ambassador townhalls, where group communication happens. It's unfortunate you couldn't join the coordination meeting we've had with Marcom to decide on 2-way communication and collaboration. Should we set-up a dedicated session with you?

**Comment by idiom-bytes** [comment]
@MeMent0L 
Let's put it in the ocean ecosystem calendar, host in on discord, make it public, gather notes, etc...
Let's have the marcom team join us there.
Let's do this like everything else.

Think "DAOStack". Let's operate together.

Can you tag who from MarCom?
@MonicaBotez @CasianaOcean @AnaLoznianu ?

**Comment by MeMent0L** [comment]
We've discussed with @MonicaBotez. Next meeting is on Thursday Jan 13th, 4:30pm UTC, and then every 2nd Thursday of the month at the same time. Looking forward to have you onboard!
