### ISSUE TITLE
Formalize + Implement the processes & tooling required to establish the PGWG workflows.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/oceandao#86]
#### Overview
The Project-Guiding Working Group (PGWG) has been established to introduce a social layer on top of the grants process & OceanDAO ecosystem.

The goal of the PGWG is to provide a human layer that connects participants, provides mentorship, and establishes support systems for all contributors and voters. 

#### Key Processes
For each of the processes below, we need participants that understand them, are able to execute them, and have the right tools in place to enable the process to scale in a healthy, decentralized, and autonomous manner.

These processes are:
- Onboarding new members
- Onboarding grantees & proposals
- Reviewing projects & proposals
- Summarizing & supporting proposals
- Review project updates & grant deliverable
- Re-engaging with previous teams
- Coordinape voting epochs
- Coordinape funding distribution

Possible tools that will empower this WG to achieve this may be:
- Forms that can be filled by prospering members & grantees 
- Spreadsheets that track grantees & members, proposals submitted, last contact established, proposal & update reviews
- Conference calls & Calendly to connect all participants
- Recordings from calls & discussions to increase transparency and mentorship opportunities
- Proposal & Grant Update summaries that dig into each project and provide structured feeedback that can be consumed by all OceanDAO participants
- Posts on port, discord #pgwg, discord #oceandao, twitter, and other places, that provide support and visibility towards these participants

#### DOD:
- [x] Members have been onboarded
- [x] Processes have been established
- [x] WG has executed all processes at least once

**Comment by idiom-bytes** [comment]
(1) For further insights and concepts behind this Epic & deliverables, please refer to proposal submitted to Port for Round 12:
- https://port.oceanprotocol.com/t/project-guiding-work-group-rewards/1190
- PGWG "Evaluators" in the proposal are equivalent to the Processes described in **[Key Processes]**.

(2) Please refer to @realdatawhale WRT to "[Auditing Framework](https://port.oceanprotocol.com/t/project-guiding-work-group-rewards/1190/10?u=idiom-bytes)" that Evaluators could do. This is equivalent to **Key Process - Review project updates & grant deliverable** and provides some direction as to how this should look-like for the end-user (voter) inside Port when they are learning about the proposals.

> Personally, I’d love to have a “digestable” executive summary on each proposal that was written within a pre-defined audit framework.

**Comment by drprk** [comment]
I believe this EPIC to be a conglomeration of Github issue #83 & #85 .

Apart from the pointers mentioned in previous threads that brought in suggestions wrt to Discourse, other forum options and payment streams, we can continue on the following logistics.

- Define parameters for PG-leaders/evaluators viz. Not just one defining parameter to qualify as a guiding voice
- Shortlist the best forum approach with features that govern for engagement & recognition, friction-less onboarding, strong sense of familiarity & allowing for quantitative voting epochs.
- Decide on funding distribution.

**PG-WG Leaders:**

- A mix of both Tech & non-tech group members with a diverse background and alignment to common goals
- PG-WG should also be open to lurkers of discord who are usually hesitant to submit for proposals. This could lead to sustained interest towards applying for upcoming grants.
- Event/call co-ordinators can also play a part 
- Come up with attractive social tiers/Early contributor tags to those who participate on a decided time interval

**PG-WG roles and responsibilities:**

- Techno-social guidance for Projects & other suitable roles thereof
- PG auditors who would assist in giving a very understanding summary of each call 
- In absence of auditors, Stewards/Volunteers take care of this during each session
- Maintenance of a biweekly PG-WG newsletter, that would give a summary of previous recorded calls; responsibility preferably given to the regular social auditors who are part of the call


Brainstorming on tools that will enable our process:

- Github Issues & Feature requests
- Exploring options on Discourse forum to see if it meets our needs
- Spreadsheets that keep track of monetary distribution ~ similar to how OceanAmbassadors maintain it
- **Conference calls & Calendly calls**: With reported feedback from each call for respective projects. For easier understanding, the PG-WG contribution guidance should be documented for sake of transparency & for suitable incentives
- Decide between continuing on Port/ Opt for an additional discourse that can be more customized to the needs of PG-WG

- Questions on how do we keep track of recorded calls? Wouldn't Leader **Notes** from each call be sufficient, thoughts? This can affect the CMS logistics long-term since the calls are usually 1-hourly and might be quite difficult to follow over a longer archive.

Apart from this, there should be a social pull of 'What makes Co-ordinapes special? Why should the community care?'

IMHO, If executed well PG-WG could be a very efficient Sub-DAO within the Ocean DAO, given the fact that it acts as the knowledge graph of communicating Project information to our own community members, before it dissipates to the overall community. 

Potential Roadmap suggestions for Co-ordinapes: 

- Once in a month Gather town party ( https://gather.town/app ) after successful V0.1 completion
- Successful execution from 0.1 -> 0.5
- Sub-DAO launch after at-least 5 voting epochs
- **D2D route**: Form strong connections with other DAOs outside of Ocean
- Keep the participating community happier and joyful with sub-optimal friction workflows & processes.

**Comment by scottymilat** [comment]
Hey all, the PGWG seems to be picking up some solid traction here. I'm coming in a little late so please keep that in mind wrt comments/thoughts below as I may be lacking some context.

There's clearly a need from both the OPF/Ocean stakeholder's perspective and also for new and existing DAO projects to have some form of project working group for Ocean and there are many different ways we could go about achieving this. 

I wanted to propose one potential way of moving this forward which may or may not be useful (hopefully it is!).

If we start from the perspective that the right amount of work/effort is the least amount of work possible that successfully addresses the current problem(s), then we would 1. want to clearly understand the problems this WG is solving and then 2. come up with solutions for addressing those and 3. track/monitor how well we are addressing the problems the WG was set up for.

We could list out all the problems that this WG is set up to address for OPF/Ocean Stakeholders and then do the same for new and existing DAO projects (ask new and existing DAO projects what they would want/need from a PGWG like this for example). Once we have this list, we can prioritise accordingly (essentially building out our PGWG backlog). For the highest priority ones we can dig deeper to clearly identify/define them. We would then be able to identify the best solutions to address the highest priority problems.

From here we can then track/monitor how well we are doing as we progress, others can objectively review the PGWG's performance and we can course correct accordingly. Investing in this work up front will helps us lay out a plan that will be easier for new joiners to understand and begin working on. 

These are just some thoughts for consideration and some of this work may have already been done which I have missed. 

Either way I'm keen to help with this initiative however I can.

**Comment by drprk** [comment]
Thanks for joining the convo @scottymilat , very much agree with your pointers. I think the list of problems is being dissected across #83 , #85 at the moment, to go along with the Proposal on Port [ https://port.oceanprotocol.com/t/project-guiding-work-group-rewards/1190/10 ]. 

We can keep filtering the discussion points till we arrive at the V0.1 process

**Comment by idiom-bytes** [comment]
> If we start from the perspective that the right amount of work/effort is the least amount of work possible that successfully addresses the current problem(s), then we would 1. want to clearly understand the problems this WG is solving and then 2. come up with solutions for addressing those and 3. track/monitor how well we are addressing the problems the WG was set up for.

I generally agree. But also think it's important to ship first.

I was telling @Scott M3#7921 about this approach for building products called salesprocess.io and thought I'd share it here.
Most specifically this image, and how very early on your product development journey,:
1. Build out manual a manual processes that executes the outcome.
2. Identify what's painful or valuable, that can be leveraged and scaled.

I think this would be a very constructive methodology to apply to these next steps inside the PGWG.

Do the max that we can, with the minimum required. But focus on process & outcome, rather than research & learning.
As defined in The Lean Startup. Build -> Measure -> Learn

![Screenshot from 2021-12-20 15-31-19](https://user-images.githubusercontent.com/69865342/146851056-9b52070b-9a5c-4d52-800c-bf9a7ea95212.png)

**Comment by scottymilat** [comment]
Hey guys, thanks for bringing me up to speed with the conversation yesterday and sorry I had to leave to the other call. 

This is a useful clarification @idiom-bytes and +1 on the importance of shipping first. 

In summary, my understanding from yesterday is that while we aim to provide more sophisticated guidance in the future, the initial need is more straight forward. 

Key problems identified:

1. No engagement on some proposals (not good experience especially for first time proposers)
2. Downvoting on proposals with little or no feedback/context
3. Not enough members in PGWG to provide necessary guidance/feedback

There is a need for 2 main funnels to develop:

1. How can I onboard as an Evaluator
2. How can I onboard as a grantee/proposer 

I have jotted down how I understand the overall workflow for each of these below. I'm less clear on how the DAO proposer receives feedback (at least for V1). 

Hopefully this information is useful/relevant. Again I'm not sure if I've missed anything so please feel free to add/change/delete as necessary. 

Right now the most immediate problem I can see is that we don't have enough evaluators within the PGWG and so I suggest we focus on solving this problem first.

**These are the steps I see for each workflow**

![Screen Shot 2021-12-21 at 10 05 56 AM](https://user-images.githubusercontent.com/17240891/146886501-a446c96e-d31b-4451-822a-0a8f2bad9915.png)

Link to suggest edits to this diagram is here:
https://docs.google.com/presentation/d/1qkfBFFFDCOjax7X_0Q3-bBBI1J0aLjKkQvtTWpiyWHA/edit?usp=sharing

**Comment by idiom-bytes** [comment]
Hi everyone, I'm moving this task to closed. 

I believe we implemented some of these processes and have increased the number of contributors in the PGWG.

I think there are things in here that we can improve on, but I'd like to close this ticket.

**If you see anything, please feel free to create a new ticket, and reference this one as the source.**

Thank you!
